### ISSUE TITLE
Datenschutzerklärung

### ISSUE THREAD

**Issue by ITfroebel** [ITfroebel/tasks#23]
Herr Schirmer und Herr Sankowski setzen die Datenschutzerklärung anhand der Vorlage von Herrn Krogmann um.

**Comment by ITfroebel** [comment]
[Datenschutzerklärung Mai 2018 Webseite DFE.docx](https://github.com/ITfroebel/tasks/files/2093315/Datenschutzerklarung.Mai.2018.Webseite.DFE.docx)

**Comment by ITfroebel** [comment]
Die Datenschutzerklärung wird von Herrn Nöll kostenpflichtig erstellt. Herr Schirmer gibt den Auftrag dazu.

**Comment by FroebelAE** [comment]
- [ Die Datenschutzerklärung muss natürlich dann auch noch online gestellt werden] 
- [ Daniel braucht wahrscheinlich auch einen Account für die Homepage, damit er Datenschutzsachen zukünftig selbst pflegen kann]

**Comment by ITfroebel** [comment]
Nachdem die Zahlung geklärt ist, würde ich dieses Issue gerne schließen. Den Zugang von Daniel können wir an anderer Stelle weiterverfolgen.
