### ISSUE TITLE
Medienkonzept

### ISSUE THREAD

**Issue by ITfroebel** [ITfroebel/tasks#33]
- [x] Broschüre zur Einsicht zu Frau Steinheimer
- [x] Broschüre zurück holen!
- [x] Team Aufstellen
- [x] Anforderungen klären
- [x] Treffen organisieren
- [x] Tagesordnung vorschlagen

**Comment by ITfroebel** [comment]
- [ ] Dokumente auf iPad-computer laden
- [ ] Durcharbeiten -> Anforderungen klären

**Comment by ITfroebel** [comment]
- [ ] Ausarbeitungen an Frau Angerer zur Ansicht senden

**Comment by ITfroebel** [comment]
[Medienkonzept.pdf](https://github.com/ITfroebel/tasks/files/2514972/Medienkonzept.pdf)

**Comment by SKnoke** [comment]
Vorschlag für eine Gliederung des Medienkonzepts:

1. Ziele

2. Medienausstattung
- PCs
- Notebooks (Klasse / Schule)
- MacBooks
- Smartboard
- Beamer
- Netzwerk
- Drucker etc

3. Lehrerarbeitsplätze
- Zweck: Unterrichtsvorbereitung, Verfassen von Dokumenten (Zeugnisse etc)
- Standorte
- Verfügbare Softwarelizenzen

4. Kommunikationsmedien (UK)
- UK-iPads
- UK Koffer

5. Lernmedien (Lesen, Schreiben, Rechnen etc.)
- Arbeits-iPads
- PCs
- Smartboard

6. Verwaltung
- Netzwerk Administration
- iPad Administration (Apple-ID, VPP)
- sonstige IT

7. Anschaffung
- Spendengelder (Förderverein)
- Schulamt

8. Verankerung im Kollegium
- Fortbildungen
- Evaluation

**Comment by ITfroebel** [comment]
Bei dem Treffen mit Herrn Nöll am Donnerstag, den 17.01.2019 kam der Vorschlag auf, auch die Website im Medienkonzept zu verankern. Dies wäre dann entweder eine eigener Punkt nach 5. Lernmedien oder eine Unterpunkt zu 6. Verwaltung.
