### ISSUE TITLE
Termin mit Frau Steinheimer und Herr Nöll

### ISSUE THREAD

**Issue by FroebelAE** [ITfroebel/tasks#42]
Aktueller Stand ist ja die mail von Sebastian vom 10.12.: "Wir können gerne mal einen Montag oder Donnerstag anpeilen, muss nur mal schauen zu welcher Zeit, am liebsten wäre mir gegen Vorabend, wenn ihr das einrichten könnt." 

Wie sieht es nach den Ferien da bei euch aus? Ich könnte bezogen auf Montage und Donnerstage am 14.1.; 17.1.; 21.1.; 24.1.; Also im Grunde kann ich montags und donnerstags in der Regel immer am Vorabend.

**Comment by FroebelAE** [comment]
- [ ] Wir müssen einen Termin finden

- [ ] Termin mit Sebastian abklären

- [ ] Termin mit Frau Steinheimer abklären

**Comment by ITfroebel** [comment]
der 17. januar ist vorgeschlagen. frau steinheimer hat schon mündlich zugesagt und wird noch eine mail dazu schreiben

**Comment by FroebelAE** [comment]
> 
> 
> der 17. januar ist vorgeschlagen. frau steinheimer hat schon mündlich zugesagt und wird noch eine mail dazu schreiben

Die Frage ist natürlich  noch ob Lukas da kann...

**Comment by FroebelAE** [comment]
Hier können wir vielleicht auch einen Themenspeicher für das Gespräch starten. Folgende Dinge sollten meiner Meinung nach bei dem Termin angesprochen werden:

- Zukünftige Zusammenarbeit mit Herr Nöll

- Aufgabenverteilung Homepage: Welche Aufgaben gibt es aktuell, welche Aufgaben kämen nach dem Umzug zum Schulamt dazu? Wer übernimmt welche Aufgabe?

**Comment by FroebelAE** [comment]
Termin ist der 17.1.19 um 17 Uhr.

**Comment by ITfroebel** [comment]
Der Termin hat stattgefunden. Das Protokoll dazu können wir gerne auch hier noch weiter diskutieren. Solange lasse ich das Issue offen.
