### ISSUE TITLE
Umzug zum Schulamt

### ISSUE THREAD

**Issue by FroebelAE** [ITfroebel/tasks#45]
Hier könnten wir darüber sprechen, welche Dinge für den Umzug der HP zum Schulamt geklärt werden müssen.

**Comment by FroebelAE** [comment]
Wichtig ist auf jeden Fall, dass die E-Mail-Adressen möglichst ohne Unterbrechung nutzbar sind, da darunter ja auch die E-Mail ist, die Frau Rölz jeden Tag für ihre Arbeit nutzt.

**Comment by ITfroebel** [comment]
Hier ist auch nach dem Treffen vom Donnerstag noch offen, ob es rechtliche Bedenken gibt, die Schulwebsite durch einen unabhängigen Anbieter zu betreiben.

Stenzel (Panorama-Schule)/Manfred Stich (Johannes Kontschak) sind Ansprechpartner für eine mögliche Nachfrage, außerdem Herr Wattendorf vom Schulamt und die Medienetage in Dreieich.

**Comment by FroebelAE** [comment]
Verstehe ich das Schließen dieses Post dahingehend richtig, dass folgendes geklärt wurde?:

> Hier ist auch nach dem Treffen vom Donnerstag noch offen, ob es rechtliche Bedenken gibt, die Schulwebsite durch einen unabhängigen Anbieter zu betreiben.

**Comment by ITfroebel** [comment]
Herr Wattendorf, Stenzel (Panorama-Schule)/Manfred Stich (Johannes Kontschak) sind Ansprechpartner für eine Nachfrage.

**Comment by ITfroebel** [comment]
Herr Demeter hat in einem Telefonat vom 27.03. darauf hingewiesen, dass die Person, auf die die Domain eingetragen ist, letztlich verantwortlich für die Inhalte ist. Im Idealfall sollte das der Förderverein der Fröbelschule sein. Ansonsten haben wir das Impressum bereits richtig abgefasst, nämlich mit der Schulleitung als Hauptverantwortlicher. 
Wir können nun unser Impressum und unsere Datenschutzerklärung mit der vom Medienzentrum nochmal vergleichen. Dort können wir auch Teile entnehmen ohne urheberrechtliche Belange zu verletzen oder Konsequenzen aus einer solchen Verletzung befürchten zu müssen.
https://www.medienzentrum-offenbach.de/j/privacy
https://www.medienzentrum-offenbach.de/about/

**Comment by FroebelAE** [comment]
Wie ist das denn aktuell? Auf wen ist die Homepage denn eingetragen? Frau Steinheimer? Und warum sollte das idealerweise der Förderverein sein? Was hat der denn mit der ganzen Geschichte zu tun?

Impressum und Datenschutzerklärung stammen ja von Sebastian Nöll, für die wir auch bezahlt haben. Eigentlich sollte das doch gut und richtig sein, oder?

**Comment by ITfroebel** [comment]
Aktuell ist Frau Steinheimer eingetragen. Wenn man den Förderverein einträgt hat das den einfachen und praktischen Vorteil, dass man den Eintrag seltener wechseln muss. Letztlich ist es eine Formfrage. Die einzige echte Auswirkung, die es u.U. haben würde ist, dass eine Zustellung im Fall bspw. einer Beschwerde einen anderen Empfänger hätte. Damit wird die Schulleitung entlastet und der Verein in seiner Kontrollfunktion unterstützt. Frau Berg und Frau Elsuni waren damit einverstanden. Gibt es von Euch aus Bedenken über die Eintragung des Fördervereins als Verantwortlichen der Domain?

**Comment by ITfroebel** [comment]
Das von SN erstellte Impressum und die Datenschutzerklärung entsprechen nach meiner Einschätzung der Empfehlung des Medienzentrums.

**Comment by FroebelAE** [comment]
Erstmal danke fürs Kümmern. Nun zum Thema: Ehrlichgesagt wundert es mich etwas, dass Frau Berg dem ganzen zugestimmt hat. Auf einer der letzten GK ging es nämlich auch um den Förderverein und eben darum, dass der gerade am zusammenbrechen ist und dass den Frau Steinheimer und Frau Berg übernehmen werden, zumindest solange, bis wieder was von Elternseite kommt. Das allerdings wollten sie vorher nochmal juristisch abklären, denn es ist nicht ganz sicher, ob sie das in ihrer Rolle als Schulleitung überhaupt machen dürfen. Deshalb wundert es mich, dass Frau Berg zugestimmt hat, das auf den Förderverein umzuschreiben, wo dieser doch gerade so halb am untergehen ist. 

Ganz ausschließen, dass ich da jetzt irgendwie ein Gremium durcheinander bringe, möchte ich aber auch nicht. Deshalb: Lukas, das war doch so, oder?

**Comment by FroebelAE** [comment]
Und das Impressum und die Datenschutzerklärung hatte ich auch mit der vom Medienzentrum verglichen und denke auch das passt.

**Comment by ITfroebel** [comment]
@FroebelAE dann müssen wir schnelle die Website umschreiben, bevor der Verein weg ist ;-P

Nein, ernsthaft: Ich denke das ist ordentlicher. Was im Verein dann intern geschieht ist wieder eine andere Geschichte. Ich meine, wenn es derzeit niemanden gibt, der die Vorstandsfunktion im Verein übernehmen kann und das zeitweise über Frau Steinheimer läuft, ist das aus technischer Sicht zwar das selbe, wie wenn ihr Name direkt eingetragen wäre, formal ist es aber klarer. Aus diesem Grund und da hier kein Widerspruch kam werde ich das jetzt so in die Wege leiten.

**Comment by FroebelAE** [comment]
Also ich habe mich jetzt nochmal auf anderen Schulhomepages umgeschaut und da ist als Verantwortlicher immer die Schulleitung eingetragen. Bevor du da jetzt was in die Wege leitest: Führt das nicht am Ende zu unnötiger Arbeit auch für uns, wenn da jetzt der Förderverein eingetragen wird. Im Endeffekt müssten wir uns bei relevanten Sachen ja dann auch an den Förderverein wenden (bzw. ihn ggfls sogar zu Treffen einladen) und bisher war es zumindest immer sehr schwierig wen von denen zu erreichen (weiß ich, weil ich damals x mal versucht hatte, den Vorsitzenden für einen Artikel über den Förderverein zu erreichen). Außerdem will das ja wiegesagt eh schon keiner machen, dem Förderverien dann noch mehr Aufgaben zu geben, wird die Bereitschaft zur Mitarbeit nicht erhöhen. Dazu: Wir können aktuell auch niemandem vom Förderverein fragen, ob er das will, weil es ja gar keinen zum Ansprechen gibt....

Ich schreibe nochmal Lukas per mail, damit er mal hier reinschaut. Lass ihn uns noch zur Diskussion dazu holen, bevor wir da weitere Schritte einleiten.

**Comment by lsankowsky** [comment]
Sehe das auch wie Alex. Stand der letzten GK war, dass der Förderverein im Begriff ist, sich aufzulösen und das weitere Vorgehen unklar ist.
Ich denke, dass wir morgen bei der GK mehr dazu erfahren werden.

**Comment by FroebelAE** [comment]
Sehe ich das richtig, dass wir das mit dem Umschreiben auf den Förderverein jetzt erstmal lassen?

**Comment by ITfroebel** [comment]
Ich habe jetzt erstmal nichts mehr unternommen, werde aber am Montag mit Frau Steinheimer darüber sprechen.

**Comment by FroebelAE** [comment]
Was war das Ergebnis des Gesprächs, auf das du dich am 28.6. bezogen hast? 

Und noch eine andere Frage zum Thema Hosting über einen externen Anbieter.
Am 27.3. hattest du geschrieben 

> Herr Demeter hat in einem Telefonat vom 27.03. darauf hingewiesen, dass die Person, auf die die Domain eingetragen ist, letztlich verantwortlich für die Inhalte ist.

Verstehe ich das richtig, dass das bedeutet, dass es prinzipiell ok ist, wenn Herr Nöll die Homepage hostet, solange Frau Steinheimer die Verantwortung dafür trägt? Das war ja eine Frage, die wir hier zumindest noch nicht abschließend geklärt hatten. Die Überlegung war ja, dass wir die Homepage bei Sebastian Nöll lassen, **falls** es keine rechtlichen Bedenken wegen dem Hosting bei ihm gibt.

**Comment by ITfroebel** [comment]
Das Ergebnis vom Gespräch mit Frau Steinheimer war, dass wir es bis auf weiteres auf ihren Namen laufen lassen. Herr Nöll kann so das Hosting weiter führen und Frau Steinheimer ist für die Inhalte verantwortlich. In diesem Sinne würde ich dieses Issue gerne schließen, wenn nochmal Fragen auftauchen, machen wir ein neues auf, einverstanden?
