### ISSUE TITLE
SSL für Homepage

### ISSUE THREAD

**Issue by FroebelAE** [ITfroebel/tasks#47]
Sebastian hat ja in der mail vom 16.12. angeregt, die Homepage auf SSL umzustellen. Davon habe ich leider keine Ahnung. 

Daniel hat ja schon per mail nachgefragt, ob es zwingend notwendig ist und ob es keine kostenfreie Variante gibt. Sebastian hat dann geantwortet, dass es wohl ratsam ist und dass das die günstigste Variante ist.

Die Frage also: Machen wir das? 

Falls wir das für richtig empfinden, müssen wir das wegen den 150€ natürlich noch von Frau Steinheimer absegnen lassen.

**Comment by FroebelAE** [comment]
Zitat von meinem Protokoll zum Treffen am 17.1.19:

"Sebastian will sich um die SSL-Verschlüsselung kümmern und sich wieder melden. Frau Steinheimer hat die Finanzierung zugesichert."

**Comment by ITfroebel** [comment]
https ist jetzt der Standard für die Verbindung mit der Website. Das Zertifikat ist mit Let's encrypt ausgestellt und wir von safari auf macOS und firefox auf linux angenommen. Chrome auf Android geht noch nicht automatisch über den verschlüsselten Zugang auf die Seite.

**Comment by FroebelAE** [comment]
Top! Verzeihe meine Unwissenheit, aber mit Verschlüsselung kenne ich mich so gar nicht aus. Du schreibst bei Android: "geht noch nicht". Bedeutet das, dass von uns noch was diesbezüglich gemacht werden muss, oder ist das jetzt so und dabei bleibt es? Dann wäre der Punkt hier ja fertig und somit zu schließen.

**Comment by ITfroebel** [comment]
Wie sich herausgestellt hat, war das let's-encrypt zertifikat eine Übergangslösung. Jetzt ist das Zertifikat von AlphaSSL installiert. Das ist so wie es sein soll. Ich könnt, wenn Ihr wollt nochmal testen, ob das Zertifikat von allen Euren Geräten angenommen wird. Dazu einfach auf die Seite gehen. Wenn links neben der URL ein Schloss erscheint, ist eigentlich schon alles gut. Wenn Ihr es aber ganz sauber haben wollt, dann clickt Ihr auf das Schloss und überprüft das Zertifikat in dem Fester, das dann aufgeht. Interessant ist vor allem der Punkt "ausgestellt von:"

**Comment by ITfroebel** [comment]
Ich habe jetzt auf allen mir zur Verfügung stehenden Gerätetypen getestet, insbesondere auf firefox und internet explorer. Überall wurde auf die verschlüsselte Seite weitergeleitet und das Zertifikat war von AlphaSSL. Damit ist das Issue geschlossen. Wenn es bei Euch noch Probleme gibt, macht Ihn einfach wieder auf und schreibt einen Kommentar.
