### ISSUE TITLE
Autoresponder für schulsozialarbeit

### ISSUE THREAD

**Issue by ITfroebel** [ITfroebel/tasks#68]
Auf dem neuen Server muss ein automatische Antwort auf alle Mails an schulsozialarbeit erfolgen mit der korrigierten e-Mail Adresse (vgl. Mail vom 28.06.)

**Comment by FroebelAE** [comment]
Ist das etwas, das ich oder Lukas machen müssen oder ist das eine Erinnerung an dich Björn? Hat das mit der neuen E-Mail von Frau Rölz zu tun? Dass Frau Rölz eine neue E-Mail hat, habe ich nur nebenbei mitbekommen, als Lukas sie auf der Homepage geändert hat.

**Comment by ITfroebel** [comment]
Das ist für mich. Ich versuche neue Tasks immer auch jemandem zuzuordnen. Das heißt, wenn ihr nicht in der Assignee-Liste steht, könnte Ihr zwar gerne kommentieren, müsst aber nichts machen... also, so habe ich mir das gedacht. Macht das Sinn für Euch?

**Comment by FroebelAE** [comment]
Ah ok, ja das macht durchaus Sinn. Ich habe nur noch nie auf dieses "Assignees" geachtet, weil wir es bisher nie benutzt haben. Aber dann weiß ich jetzt bescheid und freue mich dazu nix machen zu müssen :)

**Comment by FroebelAE** [comment]
Wo wir aber gerade bei der Mail von Frau Rölz sind: Karins E-Mail wurde ja im HP-Aritkel geändert: Karin benutzt jetzt also eine eigene E-Mail, korrekt? Was ist mit der alten, soll die ihr weiter zu Verfügung stehen? Hast du Björn das im Blick / du verwaltest jetzt die E-Mails, oder?

**Comment by lsankowsky** [comment]
Ich würde Karin bei der nächsten gelegentlich mal fragen, ob und wie lange sie diese Adresse noch benötigt und dann hier bescheid geben.

**Comment by ITfroebel** [comment]
Danke für Dein Engagement @lsankowsky, aber das dürfte eigentlich nicht notwendig sein und führt im Zweifelsfall eher zu Verwirrung. Ihr könnt Rückfragen bezüglich der Verwendung dieser Adresse gerne an mich richten. Ich prüfe das dann entsprechend.

**Comment by ITfroebel** [comment]
Der Autoresponder ist eh schon eingerichtet. Ich würde Euch bitten, alles so zu lassen, wie es ist. Wir können das Löschen der Mailadresse gerne in einem neuen Task terminieren, nicht aber vor Ende diesen Jahres, einverstanden?
